import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";
import { ButtonMenu } from "./components/Button";
import { CartProvider } from "./cart/cartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<CartProvider>
					<div className="container">
						<Link href="/">
							<h1 className="mainHeading">Doggo Ipsum</h1>
						</Link>
						<ButtonMenu />
						{children}
					</div>
				</CartProvider>
			</body>
		</html>
	);
}
